
version : "3"

services:

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes: 
      - wordpress_data:/var/www/html
    restart: unless-stopped

volumes:
  wordpress_data:
   driver: local
   driver_opts:
    type: none
    device: /home/houazzan/data/wordpress
    o: bind
