
version : "3"

services:

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes: 
      - wordpress_data:/var/www/html
    restart: unless-stopped

    #bonus 

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ouzhamza/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ouzhamza/data/wordpress
      o: bind
